/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Mon Feb 19 12:32:59 2024 */

/* parameterized module instance */
pll1 __ (.CLKI( ), .CLKOP( ), .CLKOS2( ));
