/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Tue Feb 13 16:56:30 2024 */

/* parameterized module instance */
pll1 __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS2( ));
