//===========================================================================
// Verilog module generated by IPexpress    02/20/2024    12:51:05       
// Filename: dsi_to_cmos_params.v                                      
// IP package: D-PHY to CMOS 1.3                           
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================
`define   RX_CLK_MODE_HS_ONLY
`define   RX_TYPE_DSI
`define   NUM_RX_LANE_4
`define   RGB888
`define   TX_WAIT_LESS_15MS
`define   RX_GEAR_8
`define   NUM_TX_CH_1
