//===========================================================================
// Verilog file generated by Clarity Designer    02/20/2024    12:51:05  
// Filename: dsi_to_cmos_inst.v   IP package: D-PHY to CMOS 1.3
// Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
//===========================================================================

dsi_to_cmos dsi_to_cmos_inst (
  .reset_n_i           (reset_n_i),
// DPHY interface 
  .clk_p_i             (clk_p_i),
  .clk_n_i             (clk_n_i),
  .d0_p_io             (d0_p_io),
  .d0_n_io             (d0_n_io),
  .d1_p_i              (d1_p_i),
  .d1_n_i              (d1_n_i),
  .d2_p_i              (d2_p_i),
  .d2_n_i              (d2_n_i),
  .d3_p_i              (d3_p_i),
  .d3_n_i              (d3_n_i),
// Pixel clock, control, and data
  .clk_pixel_o         (clk_pixel_o),   // center aligned
  .vsync_o             (vsync_o),
  .hsync_o             (hsync_o),
  .de_o                (de_o),
  .pd_red_o            (pd_red_o),
  .pd_green_o          (pd_green_o),
  .pd_blue_o           (pd_blue_o)
);

