--===========================================================================
-- VHDL file generated by Clarity Designer    02/20/2024    12:51:05     
-- Filename: dsi_to_cmos_inst.vhd   IP package: D-PHY to CMOS 1.3
-- Copyright(c) 2016 Lattice Semiconductor Corporation. All rights reserved. 
--===========================================================================

component dsi_to_cmos
port (
  reset_n_i    : in std_logic;
-- DPHY interface 
  clk_p_i      : inout std_logic;
  clk_n_i      : inout std_logic;
  d0_p_io      : inout std_logic;
  d0_n_io      : inout std_logic;
  d1_p_i       : inout std_logic;
  d1_n_i       : inout std_logic;
  d2_p_i       : inout std_logic;
  d2_n_i       : inout std_logic;
  d3_p_i       : inout std_logic;
  d3_n_i       : inout std_logic;
-- Pixel clock, control, and data
  clk_pixel_o  : out std_logic;   -- center aligned
  vsync_o      : out std_logic;
  hsync_o      : out std_logic;
  de_o         : out std_logic;
  pd_red_o     : out std_logic_vector(7 downto 0);
  pd_green_o   : out std_logic_vector(7 downto 0);
  pd_blue_o    : out std_logic_vector(7 downto 0)
);
end component;

begin

dsi_to_cmos_inst : dsi_to_cmos
  port map (
  reset_n_i           => reset_n_i,
-- DPHY interface 
  clk_p_i             => clk_p_i,
  clk_n_i             => clk_n_i,
  d0_p_io             => d0_p_io,
  d0_n_io             => d0_n_io,
  d1_p_i              => d1_p_i,
  d1_n_i              => d1_n_i,
  d2_p_i              => d2_p_i,
  d2_n_i              => d2_n_i,
  d3_p_i              => d3_p_i,
  d3_n_i              => d3_n_i,
-- Pixel clock, control, and data
  clk_pixel_o         => clk_pixel_o,   -- center aligned
  vsync_o             => vsync_o,
  hsync_o             => hsync_o,
  de_o                => de_o,
  pd_red_o            => pd_red_o,
  pd_green_o          => pd_green_o,
  pd_blue_o           => pd_blue_o
);


